// This file is auto-generated by the Windows Forms Designer.
// It's recommended not to modify this file manually.

namespace FCP
{
    partial class MainForm
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.mainToolStrip = new System.Windows.Forms.ToolStrip();
            this.btnAddFiles = new System.Windows.Forms.ToolStripButton();
            this.btnAddFolder = new System.Windows.Forms.ToolStripButton();
            this.btnOpenArchive = new System.Windows.Forms.ToolStripButton();
            this.toolStripSeparator1 = new System.Windows.Forms.ToolStripSeparator();
            this.btnRemoveSelected = new System.Windows.Forms.ToolStripButton();
            this.btnReset = new System.Windows.Forms.ToolStripButton();
            this.toolStripSeparator2 = new System.Windows.Forms.ToolStripSeparator();
            this.btnCompress = new System.Windows.Forms.ToolStripButton();
            this.btnDecompress = new System.Windows.Forms.ToolStripButton();
            this.btnDecompressSelected = new System.Windows.Forms.ToolStripButton();
            this.mainPanel = new System.Windows.Forms.Panel();
            this.tableLayoutPanel1 = new System.Windows.Forms.TableLayoutPanel();
            this.groupProcessStatus = new System.Windows.Forms.GroupBox();
            this.lblOutputPathValue = new System.Windows.Forms.Label();
            this.lblCompressionRatioValue = new System.Windows.Forms.Label();
            this.lblCurrentActionValue = new System.Windows.Forms.Label();
            this.lblCurrentFile = new System.Windows.Forms.Label();
            this.lblOutputPath = new System.Windows.Forms.Label();
            this.lblCompressionRatio = new System.Windows.Forms.Label();
            this.lblCurrentAction = new System.Windows.Forms.Label();
            this.btnPauseResume = new System.Windows.Forms.Button();
            this.btnCancel = new System.Windows.Forms.Button();
            this.progressBar = new System.Windows.Forms.ProgressBar();
            this.groupBoxOptions = new System.Windows.Forms.GroupBox();
            this.tableLayoutPanel2 = new System.Windows.Forms.TableLayoutPanel();
            this.tableLayoutPanel4 = new System.Windows.Forms.TableLayoutPanel();
            this.txtPassword = new System.Windows.Forms.TextBox();
            this.chkPassword = new System.Windows.Forms.CheckBox();
            this.tableLayoutPanel3 = new System.Windows.Forms.TableLayoutPanel();
            this.radioShannonFano = new System.Windows.Forms.RadioButton();
            this.radioHuffman = new System.Windows.Forms.RadioButton();
            this.splitter1 = new System.Windows.Forms.Splitter();
            this.fileListView = new System.Windows.Forms.ListView();
            this.colFileName = ((System.Windows.Forms.ColumnHeader)(new System.Windows.Forms.ColumnHeader()));
            this.colSize = ((System.Windows.Forms.ColumnHeader)(new System.Windows.Forms.ColumnHeader()));
            this.colPath = ((System.Windows.Forms.ColumnHeader)(new System.Windows.Forms.ColumnHeader()));
            this.mainToolStrip.SuspendLayout();
            this.mainPanel.SuspendLayout();
            this.tableLayoutPanel1.SuspendLayout();
            this.groupProcessStatus.SuspendLayout();
            this.groupBoxOptions.SuspendLayout();
            this.tableLayoutPanel2.SuspendLayout();
            this.tableLayoutPanel4.SuspendLayout();
            this.tableLayoutPanel3.SuspendLayout();
            this.SuspendLayout();
            // 
            // mainToolStrip
            // 
            this.mainToolStrip.AllowMerge = false;
            this.mainToolStrip.CanOverflow = false;
            this.mainToolStrip.GripMargin = new System.Windows.Forms.Padding(0);
            this.mainToolStrip.ImageScalingSize = new System.Drawing.Size(32, 32);
            this.mainToolStrip.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.btnAddFiles,
            this.btnAddFolder,
            this.btnOpenArchive,
            this.toolStripSeparator1,
            this.btnRemoveSelected,
            this.btnReset,
            this.toolStripSeparator2,
            this.btnCompress,
            this.btnDecompress,
            this.btnDecompressSelected});
            this.mainToolStrip.LayoutStyle = System.Windows.Forms.ToolStripLayoutStyle.HorizontalStackWithOverflow;
            this.mainToolStrip.Location = new System.Drawing.Point(0, 0);
            this.mainToolStrip.Name = "mainToolStrip";
            this.mainToolStrip.Padding = new System.Windows.Forms.Padding(0, 5, 1, 5);
            this.mainToolStrip.RenderMode = System.Windows.Forms.ToolStripRenderMode.Professional;
            this.mainToolStrip.Size = new System.Drawing.Size(1045, 80);
            this.mainToolStrip.Stretch = true;
            this.mainToolStrip.TabIndex = 1;
            this.mainToolStrip.Text = "toolStrip1";
            // 
            // btnAddFiles
            // 
            this.btnAddFiles.Font = new System.Drawing.Font("Segoe UI", 7.8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnAddFiles.Image = global::FCP.Properties.Resources.add_file;
            this.btnAddFiles.ImageAlign = System.Drawing.ContentAlignment.TopCenter;
            this.btnAddFiles.ImageTransparentColor = System.Drawing.Color.Magenta;
            this.btnAddFiles.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.btnAddFiles.Name = "btnAddFiles";
            this.btnAddFiles.Padding = new System.Windows.Forms.Padding(3, 0, 3, 0);
            this.btnAddFiles.Size = new System.Drawing.Size(43, 70);
            this.btnAddFiles.Text = "Add\nFiles";
            this.btnAddFiles.TextAlign = System.Drawing.ContentAlignment.BottomCenter;
            this.btnAddFiles.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageAboveText;
            this.btnAddFiles.Click += new System.EventHandler(this.btnAddFiles_Click);
            // 
            // btnAddFolder
            // 
            this.btnAddFolder.Font = new System.Drawing.Font("Segoe UI", 7.8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnAddFolder.Image = global::FCP.Properties.Resources.add_folder;
            this.btnAddFolder.ImageAlign = System.Drawing.ContentAlignment.TopCenter;
            this.btnAddFolder.ImageTransparentColor = System.Drawing.Color.Magenta;
            this.btnAddFolder.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.btnAddFolder.Name = "btnAddFolder";
            this.btnAddFolder.Padding = new System.Windows.Forms.Padding(3, 0, 3, 0);
            this.btnAddFolder.Size = new System.Drawing.Size(55, 70);
            this.btnAddFolder.Text = "Add\nFolder";
            this.btnAddFolder.TextAlign = System.Drawing.ContentAlignment.BottomCenter;
            this.btnAddFolder.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageAboveText;
            this.btnAddFolder.Click += new System.EventHandler(this.btnAddFolder_Click);
            // 
            // btnOpenArchive
            // 
            this.btnOpenArchive.Font = new System.Drawing.Font("Segoe UI", 7.8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnOpenArchive.Image = global::FCP.Properties.Resources.extract;
            this.btnOpenArchive.ImageAlign = System.Drawing.ContentAlignment.TopCenter;
            this.btnOpenArchive.ImageTransparentColor = System.Drawing.Color.Magenta;
            this.btnOpenArchive.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.btnOpenArchive.Name = "btnOpenArchive";
            this.btnOpenArchive.Padding = new System.Windows.Forms.Padding(3, 0, 3, 0);
            this.btnOpenArchive.Size = new System.Drawing.Size(60, 70);
            this.btnOpenArchive.Text = "Open\nArchive";
            this.btnOpenArchive.TextAlign = System.Drawing.ContentAlignment.BottomCenter;
            this.btnOpenArchive.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageAboveText;
            this.btnOpenArchive.Click += new System.EventHandler(this.btnOpenArchive_Click);
            // 
            // toolStripSeparator1
            // 
            this.toolStripSeparator1.ForeColor = System.Drawing.SystemColors.ControlDarkDark;
            this.toolStripSeparator1.Margin = new System.Windows.Forms.Padding(5, 0, 5, 0);
            this.toolStripSeparator1.Name = "toolStripSeparator1";
            this.toolStripSeparator1.Size = new System.Drawing.Size(6, 70);
            // 
            // btnRemoveSelected
            // 
            this.btnRemoveSelected.Font = new System.Drawing.Font("Segoe UI", 7.8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnRemoveSelected.Image = global::FCP.Properties.Resources.remove_selected;
            this.btnRemoveSelected.ImageAlign = System.Drawing.ContentAlignment.TopCenter;
            this.btnRemoveSelected.ImageTransparentColor = System.Drawing.Color.Magenta;
            this.btnRemoveSelected.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.btnRemoveSelected.Name = "btnRemoveSelected";
            this.btnRemoveSelected.Padding = new System.Windows.Forms.Padding(3, 0, 3, 0);
            this.btnRemoveSelected.Size = new System.Drawing.Size(67, 70);
            this.btnRemoveSelected.Text = "Remove\nSelected";
            this.btnRemoveSelected.TextAlign = System.Drawing.ContentAlignment.BottomCenter;
            this.btnRemoveSelected.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageAboveText;
            this.btnRemoveSelected.Click += new System.EventHandler(this.btnRemoveSelected_Click);
            // 
            // btnReset
            // 
            this.btnReset.Font = new System.Drawing.Font("Segoe UI", 7.8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnReset.Image = global::FCP.Properties.Resources.reset;
            this.btnReset.ImageAlign = System.Drawing.ContentAlignment.TopCenter;
            this.btnReset.ImageTransparentColor = System.Drawing.Color.Magenta;
            this.btnReset.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.btnReset.Name = "btnReset";
            this.btnReset.Padding = new System.Windows.Forms.Padding(3, 0, 3, 0);
            this.btnReset.Size = new System.Drawing.Size(50, 70);
            this.btnReset.Text = "Reset";
            this.btnReset.TextAlign = System.Drawing.ContentAlignment.BottomCenter;
            this.btnReset.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageAboveText;
            this.btnReset.Click += new System.EventHandler(this.btnReset_Click);
            // 
            // toolStripSeparator2
            // 
            this.toolStripSeparator2.ForeColor = System.Drawing.SystemColors.ControlDarkDark;
            this.toolStripSeparator2.Margin = new System.Windows.Forms.Padding(5, 0, 5, 0);
            this.toolStripSeparator2.Name = "toolStripSeparator2";
            this.toolStripSeparator2.Size = new System.Drawing.Size(6, 70);
            // 
            // btnCompress
            // 
            this.btnCompress.Font = new System.Drawing.Font("Segoe UI", 7.8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnCompress.Image = global::FCP.Properties.Resources.compress;
            this.btnCompress.ImageAlign = System.Drawing.ContentAlignment.TopCenter;
            this.btnCompress.ImageTransparentColor = System.Drawing.Color.Magenta;
            this.btnCompress.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.btnCompress.Name = "btnCompress";
            this.btnCompress.Padding = new System.Windows.Forms.Padding(3, 0, 3, 0);
            this.btnCompress.Size = new System.Drawing.Size(77, 70);
            this.btnCompress.Text = "Compress";
            this.btnCompress.TextAlign = System.Drawing.ContentAlignment.BottomCenter;
            this.btnCompress.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageAboveText;
            this.btnCompress.Click += new System.EventHandler(this.btnCompress_Click);
            // 
            // btnDecompress
            // 
            this.btnDecompress.Font = new System.Drawing.Font("Segoe UI", 7.8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnDecompress.Image = global::FCP.Properties.Resources.extract;
            this.btnDecompress.ImageAlign = System.Drawing.ContentAlignment.TopCenter;
            this.btnDecompress.ImageTransparentColor = System.Drawing.Color.Magenta;
            this.btnDecompress.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.btnDecompress.Name = "btnDecompress";
            this.btnDecompress.Padding = new System.Windows.Forms.Padding(3, 0, 3, 0);
            this.btnDecompress.Size = new System.Drawing.Size(91, 70);
            this.btnDecompress.Text = "Decompress";
            this.btnDecompress.TextAlign = System.Drawing.ContentAlignment.BottomCenter;
            this.btnDecompress.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageAboveText;
            this.btnDecompress.Click += new System.EventHandler(this.btnDecompress_Click);
            // 
            // btnExtractSelected
            // 
            this.btnDecompressSelected.Font = new System.Drawing.Font("Segoe UI", 7.8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnDecompressSelected.Image = global::FCP.Properties.Resources.extract;
            this.btnDecompressSelected.ImageAlign = System.Drawing.ContentAlignment.TopCenter;
            this.btnDecompressSelected.ImageTransparentColor = System.Drawing.Color.Magenta;
            this.btnDecompressSelected.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.btnDecompressSelected.Name = "btnDecompressSelected";
            this.btnDecompressSelected.Padding = new System.Windows.Forms.Padding(3, 0, 3, 0);
            this.btnDecompressSelected.Size = new System.Drawing.Size(91, 70);
            this.btnDecompressSelected.Text = "Decompress\nSelected";
            this.btnDecompressSelected.TextAlign = System.Drawing.ContentAlignment.BottomCenter;
            this.btnDecompressSelected.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageAboveText;
            this.btnDecompressSelected.ToolTipText = "Decompress\r\nSelected";
            this.btnDecompressSelected.Click += new System.EventHandler(this.btnDecompressSelected_Click);
            // 
            // mainPanel
            // 
            this.mainPanel.Controls.Add(this.tableLayoutPanel1);
            this.mainPanel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.mainPanel.Location = new System.Drawing.Point(0, 80);
            this.mainPanel.Margin = new System.Windows.Forms.Padding(4);
            this.mainPanel.Name = "mainPanel";
            this.mainPanel.Padding = new System.Windows.Forms.Padding(7, 6, 7, 6);
            this.mainPanel.Size = new System.Drawing.Size(1045, 638);
            this.mainPanel.TabIndex = 3;
            // 
            // tableLayoutPanel1
            // 
            this.tableLayoutPanel1.ColumnCount = 1;
            this.tableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.tableLayoutPanel1.Controls.Add(this.groupProcessStatus, 0, 2);
            this.tableLayoutPanel1.Controls.Add(this.groupBoxOptions, 0, 1);
            this.tableLayoutPanel1.Controls.Add(this.fileListView, 0, 0);
            this.tableLayoutPanel1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tableLayoutPanel1.Location = new System.Drawing.Point(7, 6);
            this.tableLayoutPanel1.Name = "tableLayoutPanel1";
            this.tableLayoutPanel1.RowCount = 3;
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 86.57487F));
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 13.42513F));
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 97F));
            this.tableLayoutPanel1.Size = new System.Drawing.Size(1031, 647);
            this.tableLayoutPanel1.TabIndex = 4;
            // 
            // groupProcessStatus
            // 
            this.groupProcessStatus.BackColor = System.Drawing.SystemColors.ButtonFace;
            this.groupProcessStatus.Controls.Add(this.lblOutputPathValue);
            this.groupProcessStatus.Controls.Add(this.lblCompressionRatioValue);
            this.groupProcessStatus.Controls.Add(this.lblCurrentActionValue);
            this.groupProcessStatus.Controls.Add(this.lblCurrentFile);
            this.groupProcessStatus.Controls.Add(this.lblOutputPath);
            this.groupProcessStatus.Controls.Add(this.lblCompressionRatio);
            this.groupProcessStatus.Controls.Add(this.lblCurrentAction);
            this.groupProcessStatus.Controls.Add(this.btnPauseResume);
            this.groupProcessStatus.Controls.Add(this.btnCancel);
            this.groupProcessStatus.Controls.Add(this.progressBar);
            this.groupProcessStatus.Dock = System.Windows.Forms.DockStyle.Fill;
            this.groupProcessStatus.FlatStyle = System.Windows.Forms.FlatStyle.System;
            this.groupProcessStatus.Location = new System.Drawing.Point(4, 553);
            this.groupProcessStatus.Margin = new System.Windows.Forms.Padding(4);
            this.groupProcessStatus.Name = "groupProcessStatus";
            this.groupProcessStatus.Padding = new System.Windows.Forms.Padding(4);
            this.groupProcessStatus.Size = new System.Drawing.Size(1023, 90);
            this.groupProcessStatus.TabIndex = 4;
            this.groupProcessStatus.TabStop = false;
            this.groupProcessStatus.Text = "Process Status";
            // 
            // lblOutputPathValue
            // 
            this.lblOutputPathValue.AutoSize = true;
            this.lblOutputPathValue.Location = new System.Drawing.Point(724, 28);
            this.lblOutputPathValue.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.lblOutputPathValue.Name = "lblOutputPathValue";
            this.lblOutputPathValue.Size = new System.Drawing.Size(16, 16);
            this.lblOutputPathValue.TabIndex = 9;
            this.lblOutputPathValue.Text = "...";
            // 
            // lblCompressionRatioValue
            // 
            this.lblCompressionRatioValue.AutoSize = true;
            this.lblCompressionRatioValue.Location = new System.Drawing.Point(463, 27);
            this.lblCompressionRatioValue.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.lblCompressionRatioValue.Name = "lblCompressionRatioValue";
            this.lblCompressionRatioValue.Size = new System.Drawing.Size(16, 16);
            this.lblCompressionRatioValue.TabIndex = 8;
            this.lblCompressionRatioValue.Text = "...";
            // 
            // lblCurrentActionValue
            // 
            this.lblCurrentActionValue.AutoSize = true;
            this.lblCurrentActionValue.Location = new System.Drawing.Point(108, 27);
            this.lblCurrentActionValue.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.lblCurrentActionValue.Name = "lblCurrentActionValue";
            this.lblCurrentActionValue.Size = new System.Drawing.Size(16, 16);
            this.lblCurrentActionValue.TabIndex = 7;
            this.lblCurrentActionValue.Text = "...";
            // 
            // lblCurrentFile
            // 
            this.lblCurrentFile.AutoSize = true;
            this.lblCurrentFile.BackColor = System.Drawing.Color.Transparent;
            this.lblCurrentFile.Location = new System.Drawing.Point(395, 59);
            this.lblCurrentFile.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.lblCurrentFile.Name = "lblCurrentFile";
            this.lblCurrentFile.Size = new System.Drawing.Size(16, 16);
            this.lblCurrentFile.TabIndex = 10;
            this.lblCurrentFile.Text = "...";
            // 
            // lblOutputPath
            // 
            this.lblOutputPath.AutoSize = true;
            this.lblOutputPath.Font = new System.Drawing.Font("Microsoft Sans Serif", 7.8F);
            this.lblOutputPath.Location = new System.Drawing.Point(640, 27);
            this.lblOutputPath.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.lblOutputPath.Name = "lblOutputPath";
            this.lblOutputPath.Size = new System.Drawing.Size(78, 16);
            this.lblOutputPath.TabIndex = 6;
            this.lblOutputPath.Text = "Output Path:";
            // 
            // lblCompressionRatio
            // 
            this.lblCompressionRatio.AutoSize = true;
            this.lblCompressionRatio.Font = new System.Drawing.Font("Microsoft Sans Serif", 7.8F);
            this.lblCompressionRatio.Location = new System.Drawing.Point(330, 27);
            this.lblCompressionRatio.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.lblCompressionRatio.Name = "lblCompressionRatio";
            this.lblCompressionRatio.Size = new System.Drawing.Size(125, 16);
            this.lblCompressionRatio.TabIndex = 5;
            this.lblCompressionRatio.Text = "Compression Ratio:";
            // 
            // lblCurrentAction
            // 
            this.lblCurrentAction.AutoSize = true;
            this.lblCurrentAction.Font = new System.Drawing.Font("Microsoft Sans Serif", 7.8F);
            this.lblCurrentAction.Location = new System.Drawing.Point(8, 28);
            this.lblCurrentAction.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.lblCurrentAction.Name = "lblCurrentAction";
            this.lblCurrentAction.Size = new System.Drawing.Size(92, 16);
            this.lblCurrentAction.TabIndex = 4;
            this.lblCurrentAction.Text = "Current Action:";
            // 
            // btnPauseResume
            // 
            this.btnPauseResume.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.btnPauseResume.Enabled = false;
            this.btnPauseResume.Location = new System.Drawing.Point(807, 54);
            this.btnPauseResume.Margin = new System.Windows.Forms.Padding(4);
            this.btnPauseResume.Name = "btnPauseResume";
            this.btnPauseResume.Size = new System.Drawing.Size(100, 28);
            this.btnPauseResume.TabIndex = 2;
            this.btnPauseResume.Text = "Pause";
            this.btnPauseResume.UseVisualStyleBackColor = true;
            this.btnPauseResume.Click += new System.EventHandler(this.btnPauseResume_Click);
            // 
            // btnCancel
            // 
            this.btnCancel.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.btnCancel.Enabled = false;
            this.btnCancel.Location = new System.Drawing.Point(915, 54);
            this.btnCancel.Margin = new System.Windows.Forms.Padding(4);
            this.btnCancel.Name = "btnCancel";
            this.btnCancel.Size = new System.Drawing.Size(100, 28);
            this.btnCancel.TabIndex = 1;
            this.btnCancel.Text = "Cancel";
            this.btnCancel.UseVisualStyleBackColor = true;
            this.btnCancel.Click += new System.EventHandler(this.btnCancel_Click);
            // 
            // progressBar
            // 
            this.progressBar.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left)
            | System.Windows.Forms.AnchorStyles.Right)));
            this.progressBar.Location = new System.Drawing.Point(8, 53);
            this.progressBar.Margin = new System.Windows.Forms.Padding(4);
            this.progressBar.Name = "progressBar";
            this.progressBar.Size = new System.Drawing.Size(791, 28);
            this.progressBar.TabIndex = 0;
            // 
            // groupBoxOptions
            // 
            this.groupBoxOptions.BackColor = System.Drawing.SystemColors.ButtonFace;
            this.groupBoxOptions.Controls.Add(this.tableLayoutPanel2);
            this.groupBoxOptions.Dock = System.Windows.Forms.DockStyle.Fill;
            this.groupBoxOptions.Location = new System.Drawing.Point(4, 480);
            this.groupBoxOptions.Margin = new System.Windows.Forms.Padding(4);
            this.groupBoxOptions.Name = "groupBoxOptions";
            this.groupBoxOptions.Padding = new System.Windows.Forms.Padding(4);
            this.groupBoxOptions.Size = new System.Drawing.Size(1023, 65);
            this.groupBoxOptions.TabIndex = 2;
            this.groupBoxOptions.TabStop = false;
            this.groupBoxOptions.Text = "Options";
            // 
            // tableLayoutPanel2
            // 
            this.tableLayoutPanel2.ColumnCount = 3;
            this.tableLayoutPanel2.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 49F));
            this.tableLayoutPanel2.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 2F));
            this.tableLayoutPanel2.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 49F));
            this.tableLayoutPanel2.Controls.Add(this.tableLayoutPanel4, 2, 0);
            this.tableLayoutPanel2.Controls.Add(this.tableLayoutPanel3, 0, 0);
            this.tableLayoutPanel2.Controls.Add(this.splitter1, 1, 0);
            this.tableLayoutPanel2.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tableLayoutPanel2.Location = new System.Drawing.Point(4, 19);
            this.tableLayoutPanel2.Name = "tableLayoutPanel2";
            this.tableLayoutPanel2.RowCount = 1;
            this.tableLayoutPanel2.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tableLayoutPanel2.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 42F));
            this.tableLayoutPanel2.Size = new System.Drawing.Size(1015, 42);
            this.tableLayoutPanel2.TabIndex = 4;
            // 
            // tableLayoutPanel4
            // 
            this.tableLayoutPanel4.ColumnCount = 2;
            this.tableLayoutPanel4.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 38.00813F));
            this.tableLayoutPanel4.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 61.99187F));
            this.tableLayoutPanel4.Controls.Add(this.txtPassword, 1, 0);
            this.tableLayoutPanel4.Controls.Add(this.chkPassword, 0, 0);
            this.tableLayoutPanel4.Dock = System.Windows.Forms.DockStyle.Left;
            this.tableLayoutPanel4.Location = new System.Drawing.Point(520, 3);
            this.tableLayoutPanel4.Name = "tableLayoutPanel4";
            this.tableLayoutPanel4.RowCount = 1;
            this.tableLayoutPanel4.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.tableLayoutPanel4.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 36F));
            this.tableLayoutPanel4.Size = new System.Drawing.Size(492, 36);
            this.tableLayoutPanel4.TabIndex = 2;
            // 
            // txtPassword
            // 
            this.txtPassword.Dock = System.Windows.Forms.DockStyle.Fill;
            this.txtPassword.Location = new System.Drawing.Point(191, 4);
            this.txtPassword.Margin = new System.Windows.Forms.Padding(4);
            this.txtPassword.Name = "txtPassword";
            this.txtPassword.PasswordChar = '*';
            this.txtPassword.Size = new System.Drawing.Size(297, 22);
            this.txtPassword.TabIndex = 4;
            // 
            // chkPassword
            // 
            this.chkPassword.AutoSize = true;
            this.chkPassword.Location = new System.Drawing.Point(4, 4);
            this.chkPassword.Margin = new System.Windows.Forms.Padding(4);
            this.chkPassword.Name = "chkPassword";
            this.chkPassword.Size = new System.Drawing.Size(162, 20);
            this.chkPassword.TabIndex = 3;
            this.chkPassword.Text = "Encrypt with Password";
            this.chkPassword.UseVisualStyleBackColor = true;
            this.chkPassword.CheckedChanged += new System.EventHandler(this.chkPassword_CheckedChanged);
            // 
            // tableLayoutPanel3
            // 
            this.tableLayoutPanel3.ColumnCount = 2;
            this.tableLayoutPanel3.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 35.03055F));
            this.tableLayoutPanel3.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 64.96945F));
            this.tableLayoutPanel3.Controls.Add(this.radioShannonFano, 1, 0);
            this.tableLayoutPanel3.Controls.Add(this.radioHuffman, 0, 0);
            this.tableLayoutPanel3.Dock = System.Windows.Forms.DockStyle.Left;
            this.tableLayoutPanel3.Location = new System.Drawing.Point(3, 3);
            this.tableLayoutPanel3.Name = "tableLayoutPanel3";
            this.tableLayoutPanel3.RowCount = 1;
            this.tableLayoutPanel3.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.tableLayoutPanel3.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 36F));
            this.tableLayoutPanel3.Size = new System.Drawing.Size(491, 36);
            this.tableLayoutPanel3.TabIndex = 0;
            // 
            // radioShannonFano
            // 
            this.radioShannonFano.AutoSize = true;
            this.radioShannonFano.Location = new System.Drawing.Point(176, 4);
            this.radioShannonFano.Margin = new System.Windows.Forms.Padding(4);
            this.radioShannonFano.Name = "radioShannonFano";
            this.radioShannonFano.Size = new System.Drawing.Size(116, 20);
            this.radioShannonFano.TabIndex = 2;
            this.radioShannonFano.Text = "Shannon-Fano";
            this.radioShannonFano.UseVisualStyleBackColor = true;
            // 
            // radioHuffman
            // 
            this.radioHuffman.AutoSize = true;
            this.radioHuffman.Checked = true;
            this.radioHuffman.Location = new System.Drawing.Point(4, 4);
            this.radioHuffman.Margin = new System.Windows.Forms.Padding(4);
            this.radioHuffman.Name = "radioHuffman";
            this.radioHuffman.Size = new System.Drawing.Size(136, 20);
            this.radioHuffman.TabIndex = 1;
            this.radioHuffman.TabStop = true;
            this.radioHuffman.Text = "Huffman Algorithm";
            this.radioHuffman.UseVisualStyleBackColor = true;
            // 
            // splitter1
            // 
            this.splitter1.BackColor = System.Drawing.SystemColors.ControlDark;
            this.splitter1.Location = new System.Drawing.Point(500, 3);
            this.splitter1.Name = "splitter1";
            this.splitter1.Size = new System.Drawing.Size(3, 36);
            this.splitter1.TabIndex = 1;
            this.splitter1.TabStop = false;
            // 
            // fileListView
            // 
            this.fileListView.Columns.AddRange(new System.Windows.Forms.ColumnHeader[] {
            this.colFileName,
            this.colSize,
            this.colPath});
            this.fileListView.Dock = System.Windows.Forms.DockStyle.Fill;
            this.fileListView.FullRowSelect = true;
            this.fileListView.GridLines = true;
            this.fileListView.HideSelection = false;
            this.fileListView.Location = new System.Drawing.Point(4, 4);
            this.fileListView.Margin = new System.Windows.Forms.Padding(4);
            this.fileListView.Name = "fileListView";
            this.fileListView.Size = new System.Drawing.Size(1023, 468);
            this.fileListView.TabIndex = 1;
            this.fileListView.UseCompatibleStateImageBehavior = false;
            this.fileListView.View = System.Windows.Forms.View.Details;
            // 
            // colFileName
            // 
            this.colFileName.Text = "File Name";
            this.colFileName.Width = 250;
            // 
            // colSize
            // 
            this.colSize.Text = "Size";
            this.colSize.Width = 166;
            // 
            // colPath
            // 
            this.colPath.Text = "Path";
            this.colPath.Width = 635;
            // 
            // MainForm
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.SystemColors.ButtonHighlight;
            this.ClientSize = new System.Drawing.Size(1045, 718);
            this.Controls.Add(this.mainPanel);
            this.Controls.Add(this.mainToolStrip);
            this.Margin = new System.Windows.Forms.Padding(4);
            this.MaximizeBox = false;
            this.MaximumSize = new System.Drawing.Size(1063, 765);
            this.MinimizeBox = false;
            this.MinimumSize = new System.Drawing.Size(1063, 765);
            this.Name = "MainForm";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "C# Multimedia Compressor";
            this.mainToolStrip.ResumeLayout(false);
            this.mainToolStrip.PerformLayout();
            this.mainPanel.ResumeLayout(false);
            this.tableLayoutPanel1.ResumeLayout(false);
            this.groupProcessStatus.ResumeLayout(false);
            this.groupProcessStatus.PerformLayout();
            this.groupBoxOptions.ResumeLayout(false);
            this.tableLayoutPanel2.ResumeLayout(false);
            this.tableLayoutPanel4.ResumeLayout(false);
            this.tableLayoutPanel4.PerformLayout();
            this.tableLayoutPanel3.ResumeLayout(false);
            this.tableLayoutPanel3.PerformLayout();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion
        private System.Windows.Forms.ToolStrip mainToolStrip;
        private System.Windows.Forms.ToolStripButton btnAddFiles;
        private System.Windows.Forms.ToolStripButton btnAddFolder;
        private System.Windows.Forms.ToolStripButton btnRemoveSelected;
        private System.Windows.Forms.ToolStripButton btnReset;
        private System.Windows.Forms.ToolStripSeparator toolStripSeparator1;
        private System.Windows.Forms.ToolStripSeparator toolStripSeparator2;
        private System.Windows.Forms.ToolStripButton btnCompress;
        private System.Windows.Forms.ToolStripButton btnDecompress;
        private System.Windows.Forms.ToolStripButton btnDecompressSelected;
        private System.Windows.Forms.Panel mainPanel;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel1;
        private System.Windows.Forms.GroupBox groupProcessStatus;
        private System.Windows.Forms.Label lblOutputPathValue;
        private System.Windows.Forms.Label lblCompressionRatioValue;
        private System.Windows.Forms.Label lblCurrentActionValue;
        private System.Windows.Forms.Label lblOutputPath;
        private System.Windows.Forms.Label lblCompressionRatio;
        private System.Windows.Forms.Label lblCurrentAction;
        private System.Windows.Forms.Button btnPauseResume;
        private System.Windows.Forms.Button btnCancel;
        private System.Windows.Forms.ProgressBar progressBar;
        private System.Windows.Forms.GroupBox groupBoxOptions;
        private System.Windows.Forms.ListView fileListView;
        private System.Windows.Forms.ColumnHeader colFileName;
        private System.Windows.Forms.ColumnHeader colSize;
        private System.Windows.Forms.ColumnHeader colPath;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel2;
        private System.Windows.Forms.Splitter splitter1;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel4;
        private System.Windows.Forms.TextBox txtPassword;
        private System.Windows.Forms.CheckBox chkPassword;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel3;
        private System.Windows.Forms.RadioButton radioShannonFano;
        private System.Windows.Forms.RadioButton radioHuffman;
        private System.Windows.Forms.Label lblCurrentFile;
        private System.Windows.Forms.ToolStripButton btnOpenArchive;

    }
}
