// This file is auto-generated by the Windows Forms Designer.
// It's recommended not to modify this file manually.

namespace FCP
{
    partial class MainForm
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.mainToolStrip = new System.Windows.Forms.ToolStrip();
            this.btnAddFiles = new System.Windows.Forms.ToolStripButton();
            this.btnAddFolder = new System.Windows.Forms.ToolStripButton();
            this.btnRemoveSelected = new System.Windows.Forms.ToolStripButton();
            this.toolStripSeparator1 = new System.Windows.Forms.ToolStripSeparator();
            this.btnCompress = new System.Windows.Forms.ToolStripButton();
            this.btnExtract = new System.Windows.Forms.ToolStripButton();
            this.mainPanel = new System.Windows.Forms.Panel();
            this.groupProcessStatus = new System.Windows.Forms.GroupBox();
            this.lblOutputPathValue = new System.Windows.Forms.Label();
            this.lblCompressionRatioValue = new System.Windows.Forms.Label();
            this.lblCurrentActionValue = new System.Windows.Forms.Label();
            this.lblOutputPath = new System.Windows.Forms.Label();
            this.lblCompressionRatio = new System.Windows.Forms.Label();
            this.lblCurrentAction = new System.Windows.Forms.Label();
            this.btnPauseResume = new System.Windows.Forms.Button();
            this.btnCancel = new System.Windows.Forms.Button();
            this.progressBar = new System.Windows.Forms.ProgressBar();
            this.groupBoxOptions = new System.Windows.Forms.GroupBox();
            this.txtPassword = new System.Windows.Forms.TextBox();
            this.chkPassword = new System.Windows.Forms.CheckBox();
            this.radioHuffman = new System.Windows.Forms.RadioButton();
            this.radioShannonFano = new System.Windows.Forms.RadioButton();
            this.fileListView = new System.Windows.Forms.ListView();
            this.colFileName = ((System.Windows.Forms.ColumnHeader)(new System.Windows.Forms.ColumnHeader()));
            this.colSize = ((System.Windows.Forms.ColumnHeader)(new System.Windows.Forms.ColumnHeader()));
            this.colPath = ((System.Windows.Forms.ColumnHeader)(new System.Windows.Forms.ColumnHeader()));
            this.mainToolStrip.SuspendLayout();
            this.mainPanel.SuspendLayout();
            this.groupProcessStatus.SuspendLayout();
            this.groupBoxOptions.SuspendLayout();
            this.SuspendLayout();
            // 
            // mainToolStrip
            // 
            this.mainToolStrip.ImageScalingSize = new System.Drawing.Size(32, 32);
            this.mainToolStrip.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.btnAddFiles,
            this.btnAddFolder,
            this.btnRemoveSelected,
            this.toolStripSeparator1,
            this.btnCompress,
            this.btnExtract});
            this.mainToolStrip.Location = new System.Drawing.Point(0, 0);
            this.mainToolStrip.Name = "mainToolStrip";
            this.mainToolStrip.Size = new System.Drawing.Size(1045, 27);
            this.mainToolStrip.TabIndex = 1;
            this.mainToolStrip.Text = "toolStrip1";
            // 
            // btnAddFiles
            // 
            this.btnAddFiles.ImageTransparentColor = System.Drawing.Color.Magenta;
            this.btnAddFiles.Name = "btnAddFiles";
            this.btnAddFiles.Size = new System.Drawing.Size(74, 24);
            this.btnAddFiles.Text = "Add Files";
            this.btnAddFiles.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageAboveText;
            this.btnAddFiles.Click += new System.EventHandler(this.btnAddFiles_Click);
            // 
            // btnAddFolder
            // 
            this.btnAddFolder.ImageTransparentColor = System.Drawing.Color.Magenta;
            this.btnAddFolder.Name = "btnAddFolder";
            this.btnAddFolder.Size = new System.Drawing.Size(87, 24);
            this.btnAddFolder.Text = "Add Folder";
            this.btnAddFolder.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageAboveText;
            this.btnAddFolder.Click += new System.EventHandler(this.btnAddFolder_Click);
            // 
            // btnRemoveSelected
            // 
            this.btnRemoveSelected.ImageTransparentColor = System.Drawing.Color.Magenta;
            this.btnRemoveSelected.Name = "btnRemoveSelected";
            this.btnRemoveSelected.Size = new System.Drawing.Size(128, 24);
            this.btnRemoveSelected.Text = "Remove Selected";
            this.btnRemoveSelected.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageAboveText;
            this.btnRemoveSelected.Click += new System.EventHandler(this.btnRemoveSelected_Click);
            // 
            // toolStripSeparator1
            // 
            this.toolStripSeparator1.Name = "toolStripSeparator1";
            this.toolStripSeparator1.Size = new System.Drawing.Size(6, 27);
            // 
            // btnCompress
            // 
            this.btnCompress.ImageTransparentColor = System.Drawing.Color.Magenta;
            this.btnCompress.Name = "btnCompress";
            this.btnCompress.Size = new System.Drawing.Size(78, 24);
            this.btnCompress.Text = "Compress";
            this.btnCompress.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageAboveText;
            this.btnCompress.Click += new System.EventHandler(this.btnCompress_Click);
            // 
            // btnExtract
            // 
            this.btnExtract.ImageTransparentColor = System.Drawing.Color.Magenta;
            this.btnExtract.Name = "btnExtract";
            this.btnExtract.Size = new System.Drawing.Size(58, 24);
            this.btnExtract.Text = "Extract";
            this.btnExtract.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageAboveText;
            this.btnExtract.Click += new System.EventHandler(this.btnExtract_Click);
            // 
            // mainPanel
            // 
            this.mainPanel.Controls.Add(this.groupProcessStatus);
            this.mainPanel.Controls.Add(this.groupBoxOptions);
            this.mainPanel.Controls.Add(this.fileListView);
            this.mainPanel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.mainPanel.Location = new System.Drawing.Point(0, 27);
            this.mainPanel.Margin = new System.Windows.Forms.Padding(4);
            this.mainPanel.Name = "mainPanel";
            this.mainPanel.Padding = new System.Windows.Forms.Padding(7, 6, 7, 6);
            this.mainPanel.Size = new System.Drawing.Size(1045, 691);
            this.mainPanel.TabIndex = 3;
            // 
            // groupProcessStatus
            // 
            this.groupProcessStatus.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.groupProcessStatus.BackColor = System.Drawing.SystemColors.ButtonFace;
            this.groupProcessStatus.Controls.Add(this.lblOutputPathValue);
            this.groupProcessStatus.Controls.Add(this.lblCompressionRatioValue);
            this.groupProcessStatus.Controls.Add(this.lblCurrentActionValue);
            this.groupProcessStatus.Controls.Add(this.lblOutputPath);
            this.groupProcessStatus.Controls.Add(this.lblCompressionRatio);
            this.groupProcessStatus.Controls.Add(this.lblCurrentAction);
            this.groupProcessStatus.Controls.Add(this.btnPauseResume);
            this.groupProcessStatus.Controls.Add(this.btnCancel);
            this.groupProcessStatus.Controls.Add(this.progressBar);
            this.groupProcessStatus.FlatStyle = System.Windows.Forms.FlatStyle.System;
            this.groupProcessStatus.Location = new System.Drawing.Point(11, 593);
            this.groupProcessStatus.Margin = new System.Windows.Forms.Padding(4);
            this.groupProcessStatus.Name = "groupProcessStatus";
            this.groupProcessStatus.Padding = new System.Windows.Forms.Padding(4);
            this.groupProcessStatus.Size = new System.Drawing.Size(1024, 89);
            this.groupProcessStatus.TabIndex = 3;
            this.groupProcessStatus.TabStop = false;
            this.groupProcessStatus.Text = "Process Status";
            // 
            // lblOutputPathValue
            // 
            this.lblOutputPathValue.AutoSize = true;
            this.lblOutputPathValue.Location = new System.Drawing.Point(607, 28);
            this.lblOutputPathValue.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.lblOutputPathValue.Name = "lblOutputPathValue";
            this.lblOutputPathValue.Size = new System.Drawing.Size(16, 16);
            this.lblOutputPathValue.TabIndex = 9;
            this.lblOutputPathValue.Text = "...";
            // 
            // lblCompressionRatioValue
            // 
            this.lblCompressionRatioValue.AutoSize = true;
            this.lblCompressionRatioValue.Location = new System.Drawing.Point(398, 28);
            this.lblCompressionRatioValue.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.lblCompressionRatioValue.Name = "lblCompressionRatioValue";
            this.lblCompressionRatioValue.Size = new System.Drawing.Size(16, 16);
            this.lblCompressionRatioValue.TabIndex = 8;
            this.lblCompressionRatioValue.Text = "...";
            // 
            // lblCurrentActionValue
            // 
            this.lblCurrentActionValue.AutoSize = true;
            this.lblCurrentActionValue.Location = new System.Drawing.Point(108, 27);
            this.lblCurrentActionValue.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.lblCurrentActionValue.Name = "lblCurrentActionValue";
            this.lblCurrentActionValue.Size = new System.Drawing.Size(16, 16);
            this.lblCurrentActionValue.TabIndex = 7;
            this.lblCurrentActionValue.Text = "...";
            // 
            // lblOutputPath
            // 
            this.lblOutputPath.AutoSize = true;
            this.lblOutputPath.Font = new System.Drawing.Font("Microsoft Sans Serif", 7.8F);
            this.lblOutputPath.Location = new System.Drawing.Point(523, 27);
            this.lblOutputPath.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.lblOutputPath.Name = "lblOutputPath";
            this.lblOutputPath.Size = new System.Drawing.Size(78, 16);
            this.lblOutputPath.TabIndex = 6;
            this.lblOutputPath.Text = "Output Path:";
            // 
            // lblCompressionRatio
            // 
            this.lblCompressionRatio.AutoSize = true;
            this.lblCompressionRatio.Font = new System.Drawing.Font("Microsoft Sans Serif", 7.8F);
            this.lblCompressionRatio.Location = new System.Drawing.Point(265, 28);
            this.lblCompressionRatio.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.lblCompressionRatio.Name = "lblCompressionRatio";
            this.lblCompressionRatio.Size = new System.Drawing.Size(125, 16);
            this.lblCompressionRatio.TabIndex = 5;
            this.lblCompressionRatio.Text = "Compression Ratio:";
            // 
            // lblCurrentAction
            // 
            this.lblCurrentAction.AutoSize = true;
            this.lblCurrentAction.Font = new System.Drawing.Font("Microsoft Sans Serif", 7.8F);
            this.lblCurrentAction.Location = new System.Drawing.Point(8, 28);
            this.lblCurrentAction.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.lblCurrentAction.Name = "lblCurrentAction";
            this.lblCurrentAction.Size = new System.Drawing.Size(92, 16);
            this.lblCurrentAction.TabIndex = 4;
            this.lblCurrentAction.Text = "Current Action:";
            // 
            // btnPauseResume
            // 
            this.btnPauseResume.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.btnPauseResume.Enabled = false;
            this.btnPauseResume.Location = new System.Drawing.Point(808, 53);
            this.btnPauseResume.Margin = new System.Windows.Forms.Padding(4);
            this.btnPauseResume.Name = "btnPauseResume";
            this.btnPauseResume.Size = new System.Drawing.Size(100, 28);
            this.btnPauseResume.TabIndex = 2;
            this.btnPauseResume.Text = "Pause";
            this.btnPauseResume.UseVisualStyleBackColor = true;
            this.btnPauseResume.Click += new System.EventHandler(this.btnPauseResume_Click);
            // 
            // btnCancel
            // 
            this.btnCancel.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.btnCancel.Enabled = false;
            this.btnCancel.Location = new System.Drawing.Point(916, 53);
            this.btnCancel.Margin = new System.Windows.Forms.Padding(4);
            this.btnCancel.Name = "btnCancel";
            this.btnCancel.Size = new System.Drawing.Size(100, 28);
            this.btnCancel.TabIndex = 1;
            this.btnCancel.Text = "Cancel";
            this.btnCancel.UseVisualStyleBackColor = true;
            this.btnCancel.Click += new System.EventHandler(this.btnCancel_Click);
            // 
            // progressBar
            // 
            this.progressBar.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.progressBar.Location = new System.Drawing.Point(8, 53);
            this.progressBar.Margin = new System.Windows.Forms.Padding(4);
            this.progressBar.Name = "progressBar";
            this.progressBar.Size = new System.Drawing.Size(792, 28);
            this.progressBar.TabIndex = 0;
            // 
            // groupBoxOptions
            // 
            this.groupBoxOptions.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.groupBoxOptions.BackColor = System.Drawing.SystemColors.ButtonFace;
            this.groupBoxOptions.Controls.Add(this.txtPassword);
            this.groupBoxOptions.Controls.Add(this.chkPassword);
            this.groupBoxOptions.Controls.Add(this.radioHuffman);
            this.groupBoxOptions.Controls.Add(this.radioShannonFano);
            this.groupBoxOptions.Location = new System.Drawing.Point(11, 541);
            this.groupBoxOptions.Margin = new System.Windows.Forms.Padding(4);
            this.groupBoxOptions.Name = "groupBoxOptions";
            this.groupBoxOptions.Padding = new System.Windows.Forms.Padding(4);
            this.groupBoxOptions.Size = new System.Drawing.Size(1024, 44);
            this.groupBoxOptions.TabIndex = 1;
            this.groupBoxOptions.TabStop = false;
            this.groupBoxOptions.Text = "Options";
            // 
            // txtPassword
            // 
            this.txtPassword.Location = new System.Drawing.Point(633, 19);
            this.txtPassword.Margin = new System.Windows.Forms.Padding(4);
            this.txtPassword.Name = "txtPassword";
            this.txtPassword.PasswordChar = '*';
            this.txtPassword.Size = new System.Drawing.Size(205, 22);
            this.txtPassword.TabIndex = 3;
            // 
            // chkPassword
            // 
            this.chkPassword.AutoSize = true;
            this.chkPassword.Location = new System.Drawing.Point(461, 21);
            this.chkPassword.Margin = new System.Windows.Forms.Padding(4);
            this.chkPassword.Name = "chkPassword";
            this.chkPassword.Size = new System.Drawing.Size(162, 20);
            this.chkPassword.TabIndex = 2;
            this.chkPassword.Text = "Encrypt with Password";
            this.chkPassword.UseVisualStyleBackColor = true;
            this.chkPassword.CheckedChanged += new System.EventHandler(this.chkPassword_CheckedChanged);
            // 
            // radioHuffman
            // 
            this.radioHuffman.AutoSize = true;
            this.radioHuffman.Checked = true;
            this.radioHuffman.Location = new System.Drawing.Point(21, 20);
            this.radioHuffman.Margin = new System.Windows.Forms.Padding(4);
            this.radioHuffman.Name = "radioHuffman";
            this.radioHuffman.Size = new System.Drawing.Size(136, 20);
            this.radioHuffman.TabIndex = 0;
            this.radioHuffman.TabStop = true;
            this.radioHuffman.Text = "Huffman Algorithm";
            this.radioHuffman.UseVisualStyleBackColor = true;
            // 
            // radioShannonFano
            // 
            this.radioShannonFano.AutoSize = true;
            this.radioShannonFano.Location = new System.Drawing.Point(172, 20);
            this.radioShannonFano.Margin = new System.Windows.Forms.Padding(4);
            this.radioShannonFano.Name = "radioShannonFano";
            this.radioShannonFano.Size = new System.Drawing.Size(116, 20);
            this.radioShannonFano.TabIndex = 1;
            this.radioShannonFano.Text = "Shannon-Fano";
            this.radioShannonFano.UseVisualStyleBackColor = true;
            // 
            // fileListView
            // 
            this.fileListView.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.fileListView.Columns.AddRange(new System.Windows.Forms.ColumnHeader[] {
            this.colFileName,
            this.colSize,
            this.colPath});
            this.fileListView.FullRowSelect = true;
            this.fileListView.GridLines = true;
            this.fileListView.HideSelection = false;
            this.fileListView.Location = new System.Drawing.Point(7, 6);
            this.fileListView.Margin = new System.Windows.Forms.Padding(4);
            this.fileListView.Name = "fileListView";
            this.fileListView.Size = new System.Drawing.Size(1031, 527);
            this.fileListView.TabIndex = 0;
            this.fileListView.UseCompatibleStateImageBehavior = false;
            this.fileListView.View = System.Windows.Forms.View.Details;
            // 
            // colFileName
            // 
            this.colFileName.Text = "File Name";
            this.colFileName.Width = 250;
            // 
            // colSize
            // 
            this.colSize.Text = "Size";
            this.colSize.TextAlign = System.Windows.Forms.HorizontalAlignment.Right;
            this.colSize.Width = 100;
            // 
            // colPath
            // 
            this.colPath.Text = "Path";
            this.colPath.Width = 400;
            // 
            // MainForm
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.SystemColors.ButtonHighlight;
            this.ClientSize = new System.Drawing.Size(1045, 718);
            this.Controls.Add(this.mainPanel);
            this.Controls.Add(this.mainToolStrip);
            this.Margin = new System.Windows.Forms.Padding(4);
            this.MinimumSize = new System.Drawing.Size(794, 481);
            this.Name = "MainForm";
            this.Text = "C# Multimedia Compressor";
            this.mainToolStrip.ResumeLayout(false);
            this.mainToolStrip.PerformLayout();
            this.mainPanel.ResumeLayout(false);
            this.groupProcessStatus.ResumeLayout(false);
            this.groupProcessStatus.PerformLayout();
            this.groupBoxOptions.ResumeLayout(false);
            this.groupBoxOptions.PerformLayout();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion
        private System.Windows.Forms.ToolStrip mainToolStrip;
        private System.Windows.Forms.ToolStripButton btnAddFiles;
        private System.Windows.Forms.ToolStripButton btnAddFolder;
        private System.Windows.Forms.ToolStripButton btnRemoveSelected;
        private System.Windows.Forms.ToolStripSeparator toolStripSeparator1;
        private System.Windows.Forms.ToolStripButton btnCompress;
        private System.Windows.Forms.ToolStripButton btnExtract;
        private System.Windows.Forms.Panel mainPanel;
        private System.Windows.Forms.ListView fileListView;
        private System.Windows.Forms.GroupBox groupBoxOptions;
        private System.Windows.Forms.CheckBox chkPassword;
        private System.Windows.Forms.RadioButton radioHuffman;
        private System.Windows.Forms.RadioButton radioShannonFano;
        private System.Windows.Forms.ColumnHeader colFileName;
        private System.Windows.Forms.ColumnHeader colSize;
        private System.Windows.Forms.ColumnHeader colPath;
        private System.Windows.Forms.TextBox txtPassword;
        private System.Windows.Forms.GroupBox groupProcessStatus;
        private System.Windows.Forms.Button btnCancel;
        private System.Windows.Forms.ProgressBar progressBar;
        private System.Windows.Forms.Button btnPauseResume;
        private System.Windows.Forms.Label lblOutputPathValue;
        private System.Windows.Forms.Label lblCompressionRatioValue;
        private System.Windows.Forms.Label lblCurrentActionValue;
        private System.Windows.Forms.Label lblOutputPath;
        private System.Windows.Forms.Label lblCompressionRatio;
        private System.Windows.Forms.Label lblCurrentAction;
    }
}
